CI: Add linter check for scala
G-Research/spark-extension pull request #199
Opened 2023-10-09 23:52 UTC by ljubon

The goal of this PR is to enable CI to have linter enabled and basic rules defined in `.github/workflows/linter.yml`

2023-10-10 08:58 UTC, EnricoMi requested changes

2023-10-10 08:58 UTC, EnricoMi commented on .scalafmt.conf
> +
```suggestion
+rewrite.trailingCommas.style = keep

```

2023-10-10 08:58 UTC, EnricoMi commented on .github/workflows/ci.yml
> +    name: "Run linter"
```suggestion
    name: "Linting"
```

2023-10-10 08:58 UTC, EnricoMi commented on .github/workflows/ci.yml
> +    needs: [build-jvm,lint]
```suggestion
    needs: [build-jvm, lint]
```

2023-11-29 13:50 UTC, EnricoMi requested changes

2023-11-29 13:51 UTC, EnricoMi commented
How can we run scalafmt from command line / mvn so that developer can auto-format the code?

2023-11-30 08:53 UTC, EnricoMi commented
We can make scalafmt part of `mvn compile` so that this is checked during development:
- add to `pom.xml`: https://github.com/G-Research/spark-extension/pull/201/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8
- run in compile phase: https://github.com/G-Research/spark-extension/pull/212/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R247-R256

No need to add this specifically to CI then.

2023-12-27 09:55 UTC, pavlovic-ivan commented
I am good with suggested as well

2023-12-28 13:33 UTC, EnricoMi commented
All merged.

2024-01-08 20:11 UTC, closed without merging